// <auto-generated />
using System;
using DynamicSun.Weather.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DynamicSun.Weather.Infrastructure.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20250306200555_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DynamicSun.Weather.Domain.Entities.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AtmosphericPressure")
                        .HasColumnType("decimal(7,2)");

                    b.Property<double>("CloudBaseHeight")
                        .HasColumnType("decimal(7,2)");

                    b.Property<double?>("Cloudiness")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("DewPoint")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("ObjectCreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ObjectEditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("RelativeHumidity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("Temperature")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Visibility")
                        .HasColumnType("text");

                    b.Property<DateTime>("WeatherDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WeatherPhenomena")
                        .HasColumnType("text");

                    b.Property<string>("WindDirection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.ToTable("WeatherData", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
